// File: bin2gray_8.v
// Generated by MyHDL 0.10
// Date: Fri Jun  7 08:59:49 2019


//***************************************************************************
// Title : pyhdl
// Project : Python Based HDL Repository for FPGA cluster
//***************************************************************************
// File : bin2gray_8.v
// Author : Scott
// Created : Fri Jun  7 08:59:49 2019
// Last update : Fri Jun  7 08:59:49 2019
// Target Device : Xilinx
// Standard : Verilog 2003
//***************************************************************************
// Description : 
//***************************************************************************
// Generated with MyHDL Version 0.10
//***************************************************************************
// Copyright : (c) 2016
//***************************************************************************
// Revisions :
// Date     Version     Author    Description
//***************************************************************************

// Libraries and use clauses


`timescale 1ns/10ps

module bin2gray_8 (
    B,
    G
);
// Gray encoder.
// 
// B -- input intbv signal, binary encoded
// G -- output intbv signal, gray encoded
// DATA -- bit width default = 8

input [7:0] B;
output [7:0] G;
reg [7:0] G;




always @(B) begin: BIN2GRAY_8_LOGIC
    reg [9-1:0] Bext;
    integer i;
    Bext = 9'h0;
    Bext = B;
    for (i=0; i<8; i=i+1) begin
        G[i] = (Bext[(i + 1)] ^ Bext[i]);
    end
end

endmodule
